---
backend:
  - ns4_nfs
  - ns5_nfs
  - ns4_iscsi
  - ns5_iscsi
  - ns4_manila
  - ns5_manila

branch:
  - master
  - train
  - stein
  - rocky
  - queens
  - pike
  - ocata
  - newton
  - mitaka
  - liberty
  - kilo
  - juno
  - icehouse

exclude:
  - branch: icehouse
    backend: ns4_manila
  - branch: icehouse
    backend: ns5_manila
  - branch: juno
    backend: ns4_manila
  - branch: juno
    backend: ns5_manila
  - branch: kilo
    backend: ns4_manila
  - branch: kilo
    backend: ns5_manila
  - branch: liberty
    backend: ns4_manila
  - branch: liberty
    backend: ns5_manila
  - branch: mitaka
    backend: ns4_manila
  - branch: mitaka
    backend: ns5_manila
...
